console.log("hello world!")
// alert("hello world!")
console.group("main group")
console.log(20,'hello',true)
console.error("hello")
console.warn("test")
console.table({name:"test",password:"test"})
console.groupEnd()